### ISSUE TITLE
Practica de costos

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/practica-de-costos-equipo-noble#1]
[Practica de Costos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-costos-equipo-noble/files/8121221/Practica.de.Costos.pdf)

**Comment by Yabin-2021** [comment]
Calificación **20 %**

**Comment by josealfredo79** [comment]
Bien hecho y revisado
